name: Publish Package to GitHub NPM Registry

on: 
  release:
    types: [published]

jobs:
  Test-Published-Package:
    name:  Publish Package to Npm Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
    
      - name: Install Dependencies
        run: npm install

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}