name: Deployment - Reusable Workflow

on: 
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS Access Key ID for the account'

      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS Secret Access Key for the account'

      DOCKER_USERNAME:
        required: true
        description: 'Docker Username to push images'

      KUBE_CONFIG:
        required: true
        description: 'Kube Config File for the cluster'

      MONGO_USERNAME:
        required: true
        description: 'MongoDB Username for the database'

      MONGO_PASSWORD:
        required: true
        description: 'MongoDB Password for the database'

jobs:
  reuse-deploy:
    environment:
      name: development
      url: https://dev.company.com
    outputs:
      URL: ${{ steps.get-ingress-url.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Install kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: 'v1.30.0'

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set Kubecfg File
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
      - name: Fetch kubectl version
        run: | 
          kubectl version

      - name: Save Ingress IP as a GitHub Environment Variable
        run: |
          echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace Token in Manifest Files
        uses: cschleiden/replace-tokens@v1.3
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
        
      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.ENV_MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Dev Environment
        run: |
          kubectl apply -f kubernetes/development

      - name: Get Ingress URL
        id: get-ingress-url
        run: |
          echo "APP_INGRESS_HOST=$(kubectl get ingress -n ${{ vars.NAMESPACE }} -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> $GITHUB_ENV
