name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest]
                node-version: [18, 19, 20]
                exclude:
                    - operating-system: macos-latest
                      node-version: 19        
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Cache Node Modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          continue-on-error: true
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
              name: Code Coverage
              runs-on: ubuntu-latest
              steps:
              - name: Checkout Repository
                uses: actions/checkout@v4
      
              - name: Setup NodeJS Version 18
                uses: actions/setup-node@v3
                with:
                  node-version: 18
              
              - name: Cache Node Modules
                uses: actions/cache@v3
                with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
              - name: Install Dependencies
                run: npm install
          
              - name: Code Coverage
                run: npm run coverage
                continue-on-error: true
          
              - name: Archive Code Coverage
                uses: actions/upload-artifact@v3
                with:
                  name: Code-Coverage
                  path: coverage
                  retention-days: 3
      
    Build-Image:
        name: Build Docker Image
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v2.2.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ secrets.DOCKER_USERNAME }}:${{ github.sha }}
        
        - name: Test Docker Image
          run: |
               docker run --name solar-system -d \
                  -p 3000:3000 \
                  -e MONGO_URI=${{ secrets.MONGO_URI }} \
                  -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
                  -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                  ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

               wget -q -o 127.0.0.1:3000/live | grep live
               
               echo "Docker Image Test Passed"