name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest]
                node-version: [18, 19, 20]
                exclude:
                    - operating-system: macos-latest
                      node-version: 19        
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          continue-on-error: true
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
              name: Code Coverage
              runs-on: ubuntu-latest
              steps:
              - name: Checkout Repository
                uses: actions/checkout@v4
      
              - name: Setup NodeJS Version 18
                uses: actions/setup-node@v3
                with:
                  node-version: 18
          
              - name: Install Dependencies
                run: npm install
          
              - name: Code Coverage
                run: npm run coverage
                continue-on-error: true
              - name: Archive Code Coverage
                uses: actions/upload-artifact@v3
                with:
                  name: Code-Coverage
                  path: coverage
                  retention-days: 3